# OG Hacker https://github.com/IOMRC/docker_stacks/blob/master/python_aodn/Dockerfile

ARG OWNER=iosonobert
ARG BASE_CONTAINER=mrayson/jupyter_sfoda
FROM $BASE_CONTAINER

LABEL maintainer="Andrew Zulberti <andrew.zulberti@gmail.com>"

RUN pip install \
        pIMOS

USER $NB_USER


